
pool:
    vmImage: "Ubuntu-16.04"
    demands: npm

variables:
  buildConfiguration: "Release"
  wwwwrootDir:  "Tailspin.SpaceGame.Web/wwwroot"
  sdkVersion: "2.1.505"

steps:
#Donet Installer to enable us to install latest .net core pre-release version
#This is useful because it enables us to be independent of Microsoft-Hosted agent
  - task: DotNetCoreInstaller@0 
    displayName: "Use .NET Core SDK 2.1.505"
    inputs: 
      version: $(sdkVersion)

  - task: Npm@1 
    displayName: "Run Npm Install"
    inputs:
          command: "install"
          verbose: true 
     
  #This task shoul really be handled by gulp
  #By compiling the sass to css
  #This can be a contribution that I can make to the ms-learn
  #Hopefully simplifiying these sets of tasks to begins

  - script: "./node_modules/.bin/node-sass $(wwwwrootDir) --output $(wwwwrootDir)"
    displayName: "Compile scss...literally mate...."

  #You can make BuildInfor a variable
  - script: 'echo "$(Build.DefinitionName) : $(Build.BuildId) : $(Build.BuildNumber)" > buildinfo.txt'
    displayName: "Write Build Details into buildinfo.txt"
    workingDirectory: $(wwwwrootDir)

  - task: gulp@1
    displayName: "Run Gulp Task"

  #You can also add a task to cach the nuget packages for the next run
  - task: DotNetCoreCLI@2
    displayName: "Restore Project dependencies"
    inputs: 
       command: "restore"
       projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: 'Build the project - $(buildConfiguration)'
    inputs:
          command: "build"
          arguments: "--no-restore --configuration $(buildConfiguration)"
          projects: "**/*.csproj"
    
  - task: DotNetCoreCLI@2
    displayName: "Publish - $(buildConfiguration)"
    inputs:
          command: "publish"
          arguments: "--no-build --configuration $(buildConfiguration) --ouput $(Build.ArtifactStagingDirectory)/$(buildConfiguration)"
          projects: "**/*.csproj"
          zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifiact : drop"
    condition: succeeded()
       
