parameters: 
  buildConfig: "Release"


steps: 
  - task: DotNetCoreCLI@2
    displayName: "Build the project - ${{ parameters.buildConfig }}"
    inputs:
      command: "build"
      arguments: "--no-restore --configuration ${{ parameters.buildConfig }}"
      projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Publish the project - ${{ parameters.buildConfig }}"
    inputs:
      command: "publish"
      arguments: "--no-build --configuration ${{ parameters.buildConfig }} --output $(Build.ArtifactStagingDirectory)/${{parameters.buildConfig}}"
      projects: "**/*.csproj"
      publishWebProjects: false
      zipAfterPublish: true
   